name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go Run
      env:
        JULIET_POST_TOKEN: ${{ secrets.JULIET_POST_TOKEN }}
        RUN_MODE: gh-actions
      run: go run main.go

    - name: Prepare html for gh-page
      run: mkdir -p ./public && mv ./static/index.html ./public/404.html

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        # Set a generated GITHUB_TOKEN for pushing to the remote branch.
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Set Git user.name
        user_name: Lewin Lan
        # Set Git user.email
        user_email: lewin.lan.cn@gmail.com
  
